Repository material-components/material-web, pull requests merged in 2019-08, with the labels that each got.

#344 Fix imports of inert and blocking-element polyfills.
  packages/drawer/src/mwc-drawer-base.ts
Labels: cla: yes

#350 More workarounds for HTMLSlotElement and emitDecoratorMetadata bug
  packages/formfield/src/mwc-formfield-base.ts
  packages/tab-bar/src/mwc-tab-bar-base.ts
Labels: cla: yes

#349 Fix <mwc-tab-bar> layout issue in Firefox
  CHANGELOG.md
  packages/tab-bar/src/mwc-tab-bar.scss
Labels: cla: yes

#352 Add font import to demo
  demos/demo-component.css
  demos/index.html
  package-lock.json
Labels: cla: yes

#353 Fix IE11 icon rendering in <mwc-icon>
  CHANGELOG.md
  packages/icon/src/_mwc-icon.scss
Labels: cla: yes

#354 Fix <mwc-snackbar> default action/dismiss button styles.
  CHANGELOG.md
  demos/snackbar.html
  packages/snackbar/src/mwc-snackbar.scss
Labels: cla: yes

#355 Add expanded README for <mwc-snackbar>
  packages/snackbar/README.md
  packages/snackbar/images/action_and_dismiss.png
  packages/snackbar/images/action_button.png
  packages/snackbar/images/color_bb86fc.png
  packages/snackbar/images/custom_action_color.png
  packages/snackbar/images/stacked.png
  packages/snackbar/images/standard.png
Labels: cla: yes

#357 Print CSS Custom Properties of a Sass file
  package-lock.json
  package.json
  scripts/print-css-custom-properties.js
Labels: cla: yes

#356 Allow <mwc-button> open method to be called before firstUpdated
  CHANGELOG.md
  packages/snackbar/src/mwc-snackbar-base.ts
Labels: cla: yes

#358 Refactor icon-button to accept SVG or image icons
  CHANGELOG.md
  demos/icon-button.html
  packages/icon-button/src/icon-button-base.ts
  packages/icon-button/src/mwc-icon-button.scss
  test/unit/mwc-icon-button.test.js
Labels: cla: yes

#360 Add lit-analyzer to linting
  .travis.yml
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: cla: yes

#361 README for mwc-fab
  .gitignore
  demos/demo-component.css
  demos/fab.html
  packages/base/.npmignore
  packages/button/.npmignore
  packages/checkbox/.npmignore
  packages/drawer/.npmignore
  packages/fab/.npmignore
  packages/fab/README.md
  packages/fab/images/color_018786.png
  packages/fab/images/color_ffffff.png
  packages/fab/images/custom_color.png
  packages/fab/images/extended.png
  packages/fab/images/mini.png
  packages/fab/images/standard.png
  packages/formfield/.npmignore
  packages/icon-button/.npmignore
  packages/icon/.npmignore
  packages/linear-progress/.npmignore
  packages/radio/.npmignore
  packages/ripple/.npmignore
  packages/slider/.npmignore
  packages/snackbar/.npmignore
  packages/switch/.npmignore
  packages/tab-bar/.npmignore
  packages/tab-indicator/.npmignore
  packages/tab-scroller/.npmignore
  packages/tab/.npmignore
  packages/top-app-bar/.npmignore
Labels: cla: yes

#362 Only main changelog
  CHANGELOG.md
  CONTRIBUTING.md
  packages/base/CHANGELOG.md
  packages/button/CHANGELOG.md
  packages/checkbox/CHANGELOG.md
  packages/drawer/CHANGELOG.md
  packages/fab/CHANGELOG.md
  packages/formfield/CHANGELOG.md
  packages/icon-button/CHANGELOG.md
  packages/icon/CHANGELOG.md
  packages/linear-progress/CHANGELOG.md
  packages/radio/CHANGELOG.md
  packages/ripple/CHANGELOG.md
  packages/slider/CHANGELOG.md
  packages/snackbar/CHANGELOG.md
  packages/switch/CHANGELOG.md
  packages/tab-bar/CHANGELOG.md
  packages/tab-indicator/CHANGELOG.md
  packages/tab-scroller/CHANGELOG.md
  packages/tab/CHANGELOG.md
  packages/top-app-bar/CHANGELOG.md
Labels: cla: yes

#364 Remove `as any` usage with `@customElement`
  CHANGELOG.md
  packages/button/src/mwc-button.ts
  packages/checkbox/src/mwc-checkbox.ts
  packages/drawer/src/mwc-drawer.ts
  packages/fab/src/mwc-fab.ts
  packages/formfield/src/mwc-formfield.ts
  packages/icon-button/src/mwc-icon-button.ts
  packages/icon/src/mwc-icon.ts
  packages/linear-progress/src/mwc-linear-progress.ts
  packages/radio/src/mwc-radio.ts
  packages/ripple/src/mwc-ripple.ts
  packages/slider/src/mwc-slider.ts
  packages/snackbar/src/mwc-snackbar.ts
  packages/switch/src/mwc-switch.ts
  packages/tab-bar/src/mwc-tab-bar.ts
  packages/tab-indicator/src/mwc-tab-indicator.ts
  packages/tab-scroller/src/mwc-tab-scroller.ts
  packages/tab/src/mwc-tab.ts
  packages/top-app-bar/src/mwc-top-app-bar.ts
Labels: cla: yes

#363 Script to rewrite README images as permanent URLs
  .gitignore
  demos/demo-component.css
  package.json
  scripts/static-urlify-readme-images.ts
  scripts/tsconfig.json
Labels: cla: yes

#366 Better readme for button
  demos/button.html
  package.json
  packages/button/README.md
  packages/button/images/color_6200ee.png
  packages/button/images/color_ffffff.png
  packages/button/images/custom_color.png
  packages/button/images/dense.png
  packages/button/images/dense_with_icon.png
  packages/button/images/disabled.png
  packages/button/images/disabled_with_icon.png
  packages/button/images/outlind_with_icon.png
  packages/button/images/outlined.png
  packages/button/images/raised.png
  packages/button/images/raised_with_icon.png
  packages/button/images/standard.png
  packages/button/images/standard_with_icon.png
  packages/button/images/trailing_icon.png
  packages/button/images/unelevated.png
  packages/button/images/unelevated_with_icon.png
  packages/button/src/mwc-button.scss
Labels: cla: yes

#370 Split icon button toggling into its own component
  CHANGELOG.md
  demos/icon-button-toggle.html
  demos/icon-button.html
  demos/index.html
  package-lock.json
  packages/icon-button-toggle/.npmignore
  packages/icon-button-toggle/README.md
  packages/icon-button-toggle/images/custom_color_off.png
  packages/icon-button-toggle/images/custom_color_on.png
  packages/icon-button-toggle/images/disabled.png
  packages/icon-button-toggle/images/image_off.png
  packages/icon-button-toggle/images/image_on.png
  packages/icon-button-toggle/images/standard_off.png
  packages/icon-button-toggle/images/standard_on.png
  packages/icon-button-toggle/images/svg_off.png
  packages/icon-button-toggle/images/svg_on.png
  packages/icon-button-toggle/package.json
  packages/icon-button-toggle/src/icon-button-toggle-base.ts
  packages/icon-button-toggle/src/mwc-icon-button-toggle.ts
  packages/icon-button-toggle/tsconfig.json
  packages/icon-button/README.md
  packages/icon-button/images/custom_color.png
  packages/icon-button/images/disabled.png
  packages/icon-button/images/standard.png
  packages/icon-button/images/svg.png
  packages/icon-button/src/icon-button-base.ts
Labels: Component: Icon Button, cla: yes

#373 Fix broken checked property in <mwc-radio>
  CHANGELOG.md
  packages/radio/src/mwc-radio-base.ts
  test/unit/mwc-radio.test.js
Labels: cla: yes

#371 Extends ESLint from @typescript-eslint
  .eslintrc.yaml
  packages/base/src/base-element.ts
  packages/base/src/form-element.ts
  packages/base/src/observer.ts
  packages/base/src/utils.ts
  packages/button/src/mwc-button-base.ts
  packages/checkbox/src/mwc-checkbox-base.ts
  packages/drawer/src/mwc-drawer-base.ts
  packages/fab/src/mwc-fab-base.ts
  packages/formfield/src/mwc-formfield-base.ts
  packages/icon-button-toggle/src/icon-button-toggle-base.ts
  packages/icon-button-toggle/src/mwc-icon-button-toggle.ts
  packages/icon-button/src/icon-button-base.ts
  packages/icon-button/src/mwc-icon-button.ts
  packages/icon/src/mwc-icon-font.ts
  packages/icon/src/mwc-icon.ts
  packages/linear-progress/src/mwc-linear-progress-base.ts
  packages/radio/src/mwc-radio-base.ts
  packages/ripple/src/mwc-ripple-base.ts
  packages/ripple/src/ripple-directive.ts
  packages/slider/src/mwc-slider-base.ts
  packages/snackbar/src/mwc-snackbar-base.ts
  packages/switch/src/mwc-switch-base.ts
  packages/tab-bar/src/mwc-tab-bar-base.ts
  packages/tab-indicator/src/mwc-tab-indicator-base.ts
  packages/tab-scroller/src/mwc-tab-scroller-base.ts
  packages/tab/src/mwc-tab-base.ts
  packages/top-app-bar/src/mwc-top-app-bar-base.ts
  test/benchmark/helpers.ts
Labels: cla: yes

#376 Use SelectionController in <mwc-radio> even without native shadow
  packages/radio/src/mwc-radio-base.ts
  test/unit/mwc-radio.test.js
Labels: cla: yes

#377 Add README for <mwc-radio>
  demos/radio.html
  packages/radio/README.md
  packages/radio/images/color_018786.png
  packages/radio/images/custom_color.png
  packages/radio/images/standard.png
Labels: cla: yes

#378 Bump inert polyfill to fix drawer IE bug
  CHANGELOG.md
  package-lock.json
  packages/drawer/package.json
Labels: cla: yes

#382 add css custom props table to readme
  packages/notched-outline/README.md
Labels: cla: yes

#374 fix(infrastructure): use postinstall instead of custom script
  .travis.yml
  README.md
  package.json
Labels: Area: Docs, Type: Maintenance, cla: yes

#387 Fix formatting for checklist in issue template
  .github/ISSUE_TEMPLATE.md
Labels: cla: yes

#392 fix tsconfig build order
  packages/floating-label/tsconfig.json
  packages/line-ripple/tsconfig.json
  packages/notched-outline/tsconfig.json
  packages/textarea/tsconfig.json
  packages/textfield/tsconfig.json
Labels: cla: yes

#393 Fix Travis Config
  .travis.yml
Labels: cla: yes

#402 fixed lint & ran formatter
  packages/drawer/src/mwc-drawer-base.ts
  packages/radio/src/mwc-radio-base.ts
  packages/ripple/src/ripple-directive.ts
  packages/tab-bar/src/mwc-tab-bar-base.ts
  packages/textarea/src/mwc-textarea-base.ts
  packages/textarea/src/mwc-textarea.ts
  packages/textfield/src/mwc-textfield-base.ts
  packages/textfield/src/mwc-textfield.ts
Labels: cla: yes

#407 Fix lit-analyzer warning about property without attribute data.
  packages/ripple/src/mwc-ripple-base.ts
Labels: cla: yes

#396 Fall back to msMatchesSelector in findAssignedElement util
  packages/base/package.json
  packages/base/src/utils.ts
  packages/ripple/package.json
  packages/tab-scroller/package.json
Labels: cla: yes

#409 Nit: typo
  packages/notched-outline/README.md
Labels: cla: yes

#408 Make inner button element stretch to width of host
  packages/button/src/mwc-button.scss
Labels: cla: yes

#417 Re-implement `centerTitle` for MWC Top App Bar
  CHANGELOG.md
  demos/top-app-bar-fixed.html
  demos/top-app-bar-short.html
  demos/top-app-bar.html
  demos/top-app-bars/fixed.html
  demos/top-app-bars/standard.html
  packages/top-app-bar-fixed/README.md
  packages/top-app-bar-fixed/images/center_title.png
  packages/top-app-bar-short/README.md
  packages/top-app-bar-short/images/center_title.png
  packages/top-app-bar/README.md
  packages/top-app-bar/images/center_title.png
  packages/top-app-bar/src/mwc-top-app-bar-base-base.ts
  packages/top-app-bar/src/mwc-top-app-bar-base.ts
  packages/top-app-bar/src/mwc-top-app-bar.scss
Labels: cla: yes

#419 Add saucelabs environment variables
  .travis.yml
  karma.conf.js
Labels: cla: yes

#420 actually enable sauce launcher
  karma.conf.js
Labels: cla: yes

#440 Rename 3 component "base" modules for consistency
  CHANGELOG.md
  packages/icon-button-toggle/src/mwc-icon-button-toggle-base.ts
  packages/icon-button-toggle/src/mwc-icon-button-toggle.ts
  packages/icon-button/src/mwc-icon-button-base.ts
  packages/icon-button/src/mwc-icon-button.ts
  packages/top-app-bar-fixed/src/mwc-top-app-bar-fixed-base.ts
  packages/top-app-bar-fixed/src/mwc-top-app-bar-fixed.ts
Labels: Ready for Google, cla: yes
