Repository material-components/material-web, pull requests merged in 2020-04, with the labels that each got.

#1060 docs: add my config for dev to contrib guide
  README.md
Labels: cla: yes

#1068 Refactor button
  CHANGELOG.md
  packages/button/src/mwc-button-base.ts
  packages/button/src/mwc-button.scss
  packages/button/src/mwc-button.ts
  packages/button/src/test/mwc-button.test.ts
  packages/ripple/src/mwc-ripple-base.ts
  packages/ripple/src/mwc-ripple.scss
Labels: cla: yes

#1024 add tests for several packages
  package-lock.json
  package.json
  packages/button/src/test/mwc-button.test.ts
  packages/checkbox/src/test/mwc-checkbox.test.ts
  packages/drawer/src/mwc-drawer-base.ts
  packages/drawer/src/test/mwc-drawer.test.ts
  packages/fab/src/test/mwc-fab.test.ts
  packages/icon-button/src/test/mwc-icon-button.test.ts
  packages/linear-progress/src/test/mwc-linear-progress.test.ts
  packages/list/src/test/mwc-list.test.ts
  packages/menu/src/test/mwc-menu.test.ts
  packages/select/src/test/mwc-select.test.ts
  packages/slider/src/test/mwc-slider.test.ts
  packages/snackbar/src/test/mwc-snackbar.test.ts
  packages/switch/src/test/mwc-switch.test.ts
  packages/tab-bar/src/test/mwc-tab-bar.test.ts
  packages/tab/src/test/mwc-tab.test.ts
  test/src/util/helpers.ts
Labels: Focus Area: Components, Ready for Google, cla: yes

#1075 perf(menu): benchmarking
  test/src/benchmark/menu/basic.ts
Labels: cla: yes

#1081 fix(slider): min and max update UI correctly
  CHANGELOG.md
  packages/slider/src/mwc-slider-base.ts
  packages/slider/src/test/mwc-slider.test.ts
  test/src/util/helpers.ts
Labels: Ready for Google, cla: yes

#445 Implemented MDC Card Components
  demos/card.html
  demos/index.js
  package-lock.json
  packages/card-media/.npmignore
  packages/card-media/README.md
  packages/card-media/package.json
  packages/card-media/src/mwc-card-media-base.ts
  packages/card-media/src/mwc-card-media.scss
  packages/card-media/src/mwc-card-media.ts
  packages/card-media/tsconfig.json
  packages/card-primary-action/.npmignore
  packages/card-primary-action/README.md
  packages/card-primary-action/package.json
  packages/card-primary-action/src/mwc-card-primary-action-base.ts
  packages/card-primary-action/src/mwc-card-primary-action.scss
  packages/card-primary-action/src/mwc-card-primary-action.ts
  packages/card-primary-action/tsconfig.json
  packages/card/.npmignore
  packages/card/README.md
  packages/card/package.json
  packages/card/src/mwc-card-base.ts
  packages/card/src/mwc-card.scss
  packages/card/src/mwc-card.ts
  packages/card/tsconfig.json
  scripts/publish-demos.sh
  test/src/benchmark/card/test-basic.ts
  tsconfig.json
Labels: Component: Card, Focus Area: Components, cla: yes

#1093 chore: bump deps for prefix/suffix
  packages/base/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/dialog/package.json
  packages/drawer/package.json
  packages/fab/package.json
  packages/floating-label/package.json
  packages/formfield/package.json
  packages/icon-button-toggle/package.json
  packages/icon-button/package.json
  packages/line-ripple/package.json
  packages/linear-progress/package.json
  packages/list/package.json
  packages/menu/package.json
  packages/notched-outline/package.json
  packages/radio/package.json
  packages/ripple/package.json
  packages/select/package.json
  packages/slider/package.json
  packages/snackbar/package.json
  packages/switch/package.json
  packages/tab-bar/package.json
  packages/tab-indicator/package.json
  packages/tab-scroller/package.json
  packages/tab/package.json
  packages/textarea/package.json
  packages/textfield/package.json
  packages/top-app-bar-fixed/package.json
  packages/top-app-bar/package.json
Labels: cla: yes

#1048 Add Theming guide for MWC
  docs/images/color_0,0,0,38.png
  docs/images/color_0,0,0,60.png
  docs/images/color_0,0,0,87.png
  docs/images/color_000000.png
  docs/images/color_018786.png
  docs/images/color_6200ee.png
  docs/images/color_b00020.png
  docs/images/color_ffffff.png
  docs/theming.md
Labels: Focus Area: Components, Ready for Google, Severity: Medium, Type: Feature, Why: Improve documentation, cla: yes

#1099 Force using the bug, feature, and task templates
  .github/ISSUE_TEMPLATE.md
  .github/config.yml
Labels: cla: yes

#1104 docs: add start to planned component status
  README.md
Labels: cla: yes

#1162 chore: bump dep versions
  packages/base/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/dialog/package.json
  packages/drawer/package.json
  packages/fab/package.json
  packages/floating-label/package.json
  packages/formfield/package.json
  packages/icon-button-toggle/package.json
  packages/icon-button/package.json
  packages/line-ripple/package.json
  packages/linear-progress/package.json
  packages/list/package.json
  packages/menu/package.json
  packages/notched-outline/package.json
  packages/radio/package.json
  packages/ripple/package.json
  packages/select/package.json
  packages/slider/package.json
  packages/snackbar/package.json
  packages/switch/package.json
  packages/tab-bar/package.json
  packages/tab-indicator/package.json
  packages/tab-scroller/package.json
  packages/tab/package.json
  packages/textarea/package.json
  packages/textfield/package.json
  packages/top-app-bar-fixed/package.json
  packages/top-app-bar/package.json
Labels: cla: yes

#1163 chore: remove unnecessary dev deps
  package-lock.json
  package.json
Labels: cla: yes

#1239 fix(build): CI build caused by refactor snackbar
  test/src/benchmark/snackbar/test-basic.ts
Labels: Severity: Critical, cla: yes
