Repository material-components/material-web, pull requests merged in 2020-07, with the labels that each got.

#1491 fix(prod): deps up to date regarding @material/dom
  CHANGELOG.md
  lerna.json
  packages/base/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/dialog/package.json
  packages/drawer/package.json
  packages/fab/package.json
  packages/floating-label/package.json
  packages/formfield/package.json
  packages/icon-button-toggle/package.json
  packages/icon-button/package.json
  packages/icon/package.json
  packages/line-ripple/package.json
  packages/linear-progress/package.json
  packages/list/package.json
  packages/menu/package.json
  packages/notched-outline/package.json
  packages/radio/package.json
  packages/ripple/package.json
  packages/select/package.json
  packages/slider/package.json
  packages/snackbar/package.json
  packages/switch/package.json
  packages/tab-bar/package.json
  packages/tab-indicator/package.json
  packages/tab-scroller/package.json
  packages/tab/package.json
  packages/textarea/package.json
  packages/textfield/package.json
  packages/top-app-bar-fixed/package.json
  packages/top-app-bar/package.json
Labels: cla: yes

#1516 find and replace all typos with `nomodlue`
  demos/button/index.html
  demos/checkbox/index.html
  demos/dialog/index.html
  demos/drawer/index.html
  demos/drawer_dismissible/index.html
  demos/drawer_modal/index.html
  demos/drawer_standard/index.html
  demos/drawer_standard_no_header/index.html
  demos/fab/index.html
  demos/formfield/index.html
  demos/icon-button-toggle/index.html
  demos/icon-button/index.html
  demos/icon/index.html
  demos/index.html
  demos/list/index.html
  demos/menu/index.html
  demos/radio/index.html
  demos/select/index.html
  demos/slider/index.html
  demos/snackbar/index.html
  demos/switch/index.html
  demos/tabs/index.html
  demos/tabs_rtl/index.html
  demos/textarea/index.html
  demos/textfield/index.html
  demos/top-app-bar-fixed/index.html
  demos/top-app-bar-fixed_iframe/index.html
  demos/top-app-bar/index.html
  demos/top-app-bar_iframe/index.html
Labels: cla: yes

#1530 fix(demos): styles on FF
  demos/button/index.html
  demos/checkbox/index.html
  demos/dialog/index.html
  demos/drawer/index.html
  demos/drawer_dismissible/index.html
  demos/drawer_modal/index.html
  demos/drawer_standard/index.html
  demos/drawer_standard_no_header/index.html
  demos/fab/index.html
  demos/formfield/index.html
  demos/icon-button-toggle/index.html
  demos/icon-button/index.html
  demos/icon/index.html
  demos/index.html
  demos/linear-progress/index.html
  demos/list/index.html
  demos/menu/index.html
  demos/radio/index.html
  demos/ripple/index.html
  demos/select/index.html
  demos/shared/ie-style-transform.js
  demos/slider/index.html
  demos/snackbar/index.html
  demos/switch/index.html
  demos/tabs/index.html
  demos/tabs_rtl/index.html
  demos/textarea/index.html
  demos/textfield/index.html
  demos/top-app-bar-fixed/index.html
  demos/top-app-bar-fixed_iframe/index.html
  demos/top-app-bar/index.html
  demos/top-app-bar_iframe/index.html
  rollup.config.js
Labels: cla: yes

#1533 chore: bump deps
  packages/base/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/dialog/package.json
  packages/drawer/package.json
  packages/fab/package.json
  packages/floating-label/package.json
  packages/formfield/package.json
  packages/icon-button-toggle/package.json
  packages/icon-button/package.json
  packages/line-ripple/package.json
  packages/linear-progress/package.json
  packages/list/package.json
  packages/menu/package.json
  packages/notched-outline/package.json
  packages/radio/package.json
  packages/ripple/package.json
  packages/select/package.json
  packages/slider/package.json
  packages/snackbar/package.json
  packages/switch/package.json
  packages/tab-bar/package.json
  packages/tab-indicator/package.json
  packages/tab-scroller/package.json
  packages/tab/package.json
  packages/textfield/package.json
  packages/top-app-bar-fixed/package.json
  packages/top-app-bar/package.json
Labels: cla: yes

#1536 chore(slider): Stop updating MDC slider dep.
  scripts/bump-all-mdc-web-deps.ts
Labels: cla: yes

#1539 Preload fonts
  demos/button/index.html
  demos/checkbox/index.html
  demos/chips.html
  demos/dialog/index.html
  demos/drawer/index.html
  demos/drawer_dismissible/index.html
  demos/drawer_modal/index.html
  demos/drawer_standard/index.html
  demos/drawer_standard_no_header/index.html
  demos/fab/index.html
  demos/formfield/index.html
  demos/icon-button-toggle/index.html
  demos/icon-button/index.html
  demos/icon/index.html
  demos/index.html
  demos/linear-progress/index.html
  demos/list/index.html
  demos/menu/index.html
  demos/radio/index.html
  demos/ripple/index.html
  demos/select/index.html
  demos/slider/index.html
  demos/snackbar/index.html
  demos/switch/index.html
  demos/tabs/index.html
  demos/tabs_rtl/index.html
  demos/textarea/index.html
  demos/textfield/index.html
  demos/top-app-bar-fixed/index.html
  demos/top-app-bar-fixed_iframe/index.html
  demos/top-app-bar/index.html
  demos/top-app-bar_iframe/index.html
Labels: cla: yes

#1547 chore: bump-deps
  packages/base/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/dialog/package.json
  packages/drawer/package.json
  packages/fab/package.json
  packages/floating-label/package.json
  packages/formfield/package.json
  packages/icon-button-toggle/package.json
  packages/icon-button/package.json
  packages/line-ripple/package.json
  packages/linear-progress/package.json
  packages/list/package.json
  packages/menu/package.json
  packages/notched-outline/package.json
  packages/radio/package.json
  packages/ripple/package.json
  packages/select/package.json
  packages/slider/package.json
  packages/snackbar/package.json
  packages/switch/package.json
  packages/tab-bar/package.json
  packages/tab-indicator/package.json
  packages/tab-scroller/package.json
  packages/tab/package.json
  packages/textfield/package.json
  packages/top-app-bar-fixed/package.json
  packages/top-app-bar/package.json
Labels: cla: yes

#1558 Update the correct demo port
  README.md
Labels: cla: yes

#1498 Refactor `mwc-icon-button` replace ripple with lazy mwc-ripple
  CHANGELOG.md
  packages/icon-button/src/mwc-icon-button-base.ts
  packages/icon-button/src/mwc-icon-button.scss
Labels: Ready for Google, cla: yes

#1534 Refactor switch replace ripple directive with lazy mwc-ripple
  packages/switch/src/mwc-switch-base.ts
  packages/switch/src/mwc-switch.scss
Labels: Component: Ripple, Component: Switch, Focus Area: Components, Ready for Google, Why: Enable new use cases, Why: Improve performance, cla: yes

#1560 ci(format:check): make format check output more useful
  package.json
Labels: cla: yes

#1562 chore: update circular progress package files
  packages/circular-progress/.npmignore
  packages/circular-progress/tsconfig.json
  tsconfig.json
Labels: cla: yes

#1535 Fix ripple deactivate on checkbox when releasing outside of checkbox
  packages/checkbox/src/mwc-checkbox-base.ts
Labels: Ready for Google, cla: yes

#1540 Add form validation to dialog demo
  demos/dialog/index.html
  demos/dialog/index.js
Labels: cla: yes

#1589 Fix MDC deps bot
  .github/workflows/bump-mdc-deps.yml
Labels: cla: yes

#1594 Remove crossorigin errors for preload links in Chrome.
  demos/button/index.html
  demos/checkbox/index.html
  demos/chips.html
  demos/dialog/index.html
  demos/drawer/index.html
  demos/drawer_dismissible/index.html
  demos/drawer_modal/index.html
  demos/drawer_standard/index.html
  demos/drawer_standard_no_header/index.html
  demos/fab/index.html
  demos/formfield/index.html
  demos/icon-button-toggle/index.html
  demos/icon-button/index.html
  demos/icon/index.html
  demos/index.html
  demos/linear-progress/index.html
  demos/list/index.html
  demos/menu/index.html
  demos/radio/index.html
  demos/ripple/index.html
  demos/select/index.html
  demos/slider/index.html
  demos/snackbar/index.html
  demos/switch/index.html
  demos/tabs/index.html
  demos/tabs_rtl/index.html
  demos/textarea/index.html
  demos/textfield/index.html
  demos/top-app-bar-fixed/index.html
  demos/top-app-bar-fixed_iframe/index.html
  demos/top-app-bar/index.html
  demos/top-app-bar_iframe/index.html
Labels: cla: yes

#1602 chore: update tsconfig for four-color circular progress
  packages/circular-progress-four-color/.npmignore
  packages/circular-progress-four-color/tsconfig.json
  tsconfig.json
Labels: cla: yes
